plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
    id("me.modmuss50.mod-publish-plugin") version "0.8.1"

    id("com.bouncingelf10.minecraft-version-compatibility-checker") version "1.7.0"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven { url = "https://maven.terraformersmc.com/" }
    maven {
        name 'Xander Maven'
        url 'https://maven.isxander.dev/releases'
    }
    maven { url = "https://api.modrinth.com/maven" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
    implementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"
    implementation "maven.modrinth:timelesslib:${project.timelesslib_version}"
}

minecraftCompat {
    maxStrikes = 3
    bumpUp = true
}

publishMods {
    file = tasks.jar.archiveFile
    changelog = "26.1.2 port"
    type = STABLE
    modLoaders.add("fabric")

    modrinth {
        projectId = "dWUOweyL"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        requires("yacl")
        requires("modmenu")
        requires("timelesslib")
        minecraftVersions.add("26.1")
        minecraftVersions.add("26.1.1")
        minecraftVersions.add("26.1.2")
    }

    curseforge {
        projectId = "1253070"
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        requires("yacl", "modmenu", "timelesslib")
        minecraftVersions.add("26.1")
        minecraftVersions.add("26.1.1")
        minecraftVersions.add("26.1.2")
    }
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property "archivesName", project.base.archivesName
    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
}