modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL-3.0-or-later"

[[mods]]
modId = "animatedmojanglogo"
version = "${mod_version}"
displayName = "Animated Mojang Logo"
logoFile = "assets/animatedmojanglogo/icon.png"
authors = "BouncingElf10"
description = '''
Replaces the default Minecraft loading screen with the animated Mojang Studios intro from Minecraft Dungeons / Minecraft Live, including the jingle.
'''

[[dependencies.animatedmojanglogo]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animatedmojanglogo]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,1.21.4]"
ordering = "NONE"
side = "BOTH"

[[dependencies.animatedmojanglogo]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.6.1,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "animatedmojanglogo.mixins.json"